# Generated by Django 4.2.1 on 2023-05-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='nombre_pregunta',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre de la pregunta'),
        ),
    ]
